class_name FlowStates
extends RefCounted

const GAME_STATE_TITLE := 0
const GAME_STATE_PLAYING := 1
const GAME_STATE_CLEAR := 2
const GAME_STATE_PAUSED := 3
const GAME_STATE_SAVE_OPTIONS := 4
const GAME_STATE_INTRO := 5
const GAME_STATE_CHARACTER_SELECT := 6
const GAME_STATE_GAME_OVER := 7
const GAME_STATE_CHAOS_EMERALDS := 8
const GAME_STATE_TO_BE_CONTINUED := 9
const GAME_STATE_SEGA_LOGO := 10
const GAME_STATE_SONIC_TEAM := 11
const GAME_STATE_CREDITS := 12
const GAME_STATE_MISSING_EMERALDS := 13
const GAME_STATE_COPYRIGHT := 14
const GAME_STATE_SPECIAL_STAGE := 15
const GAME_STATE_CREDITS_END := 16
const GAME_STATE_CHARACTER_UNLOCK := 17
const GAME_STATE_FINAL_INTRO := 18

const ENDING_VARIANT_NORMAL := 0
const ENDING_VARIANT_FINAL := 1
const ENDING_VARIANT_EXTRA := 2

const TITLE_PHASE_PRESS_START := 0
const TITLE_PHASE_PLAY_MODE := 1
const TITLE_PHASE_SINGLE_PLAYER := 2
const TITLE_PHASE_MULTI_PLAYER := 3
const TITLE_PHASE_TIME_ATTACK := 4
const TITLE_PHASE_TINY_CHAO_GARDEN := 5
const TITLE_PHASE_MULTI_CONNECT := 6
const TITLE_PHASE_TINY_CHAO_SETUP := 7
const TITLE_PHASE_SINGLEPAK_SYNC := 8
const TITLE_PHASE_SINGLEPAK_RESULTS := 9
const TITLE_PHASE_MULTIPLAYER_LOBBY := 10
const TITLE_PHASE_TIME_ATTACK_LOBBY := 11
const TITLE_PHASE_COURSE_SELECT := 12
const TITLE_PHASE_MULTIPLAYER_OUTCOME := 13
const TITLE_PHASE_TINY_CHAO_GARDEN_PLAY := 14

const OPTIONS_MODE_MAIN := 0
const OPTIONS_MODE_PLAYER_DATA := 1
const OPTIONS_MODE_LANGUAGE := 2
const OPTIONS_MODE_BUTTON_CONFIG := 3
const OPTIONS_MODE_SOUND_TEST := 4
const OPTIONS_MODE_TIME_RECORDS := 5
const OPTIONS_MODE_MULTI_RECORDS := 6
const OPTIONS_MODE_NAME_ENTRY := 7
const OPTIONS_MODE_DIFFICULTY := 8
const OPTIONS_MODE_TIME_LIMIT := 9
const OPTIONS_MODE_DELETE_CONFIRM := 10
const OPTIONS_MODE_DELETE_CONFIRM_FINAL := 11

const TIME_RECORDS_VIEW_MODE_CHOICE := 0
const TIME_RECORDS_VIEW_COURSES := 1
const TIME_RECORDS_CONTEXT_OPTIONS := 0
const TIME_RECORDS_CONTEXT_TIME_ATTACK := 1
const SOUND_TEST_STATE_STOPPED := 0
const SOUND_TEST_STATE_PLAYING := 1
const MULTIPLAYER_RESULTS_MODE_CHARACTER_SELECTION := 0
const MULTIPLAYER_RESULTS_MODE_COURSE_COMPLETE := 1
const CHARACTER_SELECT_CONTEXT_GAME_START := 0
const CHARACTER_SELECT_CONTEXT_TIME_ATTACK_ZONE := 1
const CHARACTER_SELECT_CONTEXT_TIME_ATTACK_BOSS := 2
const CHARACTER_SELECT_CONTEXT_MULTIPLAYER := 3

const NAME_ENTRY_MATRIX_COLS := 11
# The modern profile keyboard exposes its printable character set directly:
# A-Z, 0-9, and punctuation fill four 11-key rows.
const NAME_ENTRY_MATRIX_ROWS := 4
const NAME_ENTRY_MATRIX_VISIBLE_ROWS := 4
const NAME_ENTRY_CONTROL_ROW_BACK := 4
const NAME_ENTRY_CONTROL_ROW_FORWARD := 5
const NAME_ENTRY_CONTROL_ROW_END := 6
const NAME_ENTRY_CONTROLS_COL := NAME_ENTRY_MATRIX_COLS
